# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('payback', models.FloatField(default=0)),
                ('is_ambassador', models.BooleanField(default=False)),
                ('joining_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('referral_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refearn.Customer')),
            ],
        ),
    ]
